name: Dbot test

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read

jobs:
  auto-approve-merge:
    if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      # for hmarr/auto-approve-action to approve PRs
      pull-requests: write

    steps:
    - run: echo "Hi Dependabot! How are you doing?"

    # GitHub actions bot approve
    - uses: hmarr/auto-approve-action@b40d6c9ed2fa10c9a2749eca7eb004418a705501 # v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # Nextcloud bot approve and merge request
    - uses: ahmadnassri/action-dependabot-auto-merge@45fc124d949b19b6b8bf6645b6c9d55f4f9ac61a # v2
      with:
        target: minor
        # github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
