name: Dbot test

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read

jobs:
  auto-approve-merge:
    if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      # for hmarr/auto-approve-action to approve PRs
      pull-requests: write

    steps:
    - run: echo "Hi Dependabot! How are you doing?"

    # GitHub actions bot approve
    - uses: hmarr/auto-approve-action@b40d6c9ed2fa10c9a2749eca7eb004418a705501 # v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
